### ISSUE TITLE
Nota TP N° 3

### ISSUE THREAD

**Issue by caroapaza** [aleyufra/repo-tp2#36]
Grupo 16, les dejo la nota del Trabajo Práctico N° 3: 10 (diez)

En el repositorio solo se ven commits de Alavar, Veliz y Yufra. Los alumnos Luisa Zapana y Ezequiel Villalba sigue en el grupo?
En sucursales las imagenes no se ajustan dentro de los contenedores.

Saludos.

**Comment by aleyufra** [comment]
Buenas tardes profe, Zapana si sigue en el grupo, Villalba y Véliz ya no.

**Comment by caroapaza** [comment]
> Owner

Buenas, ok, ya actualicé los integrantes del grupo.
Saludos
